### ISSUE TITLE
Very unstable behaviour under Linux with GTK

### ISSUE THREAD

**Issue by freq-mod** [takamichih/fmplayer#5]
Player tends to freeze within seconds after starting. Sometimes it possible to regain control, but most of the time killing the process is the only way to exit.

**Comment by gzaffin** [comment]
Hi freq-mod,
try this, under gtk folder try changing Makefile.am line 39 `-DPACC_GL_3` part into `-DPACC_GL_ES` and rebuild. Either if autotools have already built Makefile file, you can change Makefile and then call make as a shortcut.

Giangiacomo
